pool:
  vmImage: ubuntu-16.04

steps:
  - bash: |
      set -e
      umask 022
      if [[ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]]; then
        git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/merge:pr"
        git checkout pr
      fi
      HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew
      sudo mkdir -p /home/linuxbrew
      sudo git clone https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
      sudo mkdir -p "$HOMEBREW_REPOSITORY/Library/Taps/homebrew"
      sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-test-bot"
      sudo chown -R "$USER" /home/linuxbrew
      sudo chmod -R og-w /home/linuxbrew
    displayName: Setup Homebrew

  - bash: |
      export PATH="/home/linuxbrew/.linuxbrew/bin:/usr/bin:/bin"
      brew test-bot
    displayName: Run brew test-bot
    env:
      HOMEBREW_GITHUB_API_TOKEN: $(github.publicApiToken)

  - task: PublishTestResults@2
    displayName: Publish test-bot test results
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: brew/brew-test-bot.xml
