name: CI
on:
  push:
    branches: master
  pull_request:
jobs:
  tests:
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - os: macOS
            runner: macOS-latest
          - os: Linux
            runner: ubuntu-latest
            container:
              image: ghcr.io/homebrew/ubuntu22.04:master
              options: --user=linuxbrew
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    container: ${{ matrix.container }}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - name: Set up Ruby
        if: runner.os == 'Linux'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Install Homebrew/homebrew-test-bot RubyGems
        if: runner.os == 'macOS'
        run: bundle install --jobs 4 --retry 3

      - name: Run Homebrew/homebrew-test-bot RSpec tests
        run: bundle exec rspec

      - run: brew test-bot --only-formulae-detect --test-default-formula
        id: formulae-detect

      - id: brew-test-bot-formulae
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew test-bot \
            --only-formulae \
            --junit \
            --only-json-tab \
            --skip-dependents \
            --testing-formulae=${{ steps.formulae-detect.outputs.testing_formulae }}

      - run: |
          brew test-bot --only-formulae-dependents --junit \
                        --testing-formulae=${{ steps.formulae-detect.outputs.testing_formulae }} \
                        --skipped-or-failed-formulae=${{ steps.brew-test-bot-formulae.outputs.skipped_or_failed_formulae }}

      - name: Output brew test-bot failures
        if: runner.os == 'macOS'
        run: |
          cat steps_output.txt
          rm steps_output.txt

      - name: Output brew bottle output
        if: runner.os == 'macOS'
        run: |
          cat bottle_output.txt
          rm bottle_output.txt

      - run: brew test-bot --only-cleanup-after

      - run: brew test-bot --only-setup --dry-run

      - run: brew test-bot testbottest --only-formulae --dry-run
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
