name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request: []
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Set up Homebrew
      run: |
        brew update-reset /usr/local/Homebrew
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot"
        # Remove RubyGems that interfere with our installation.
        rm -rf /usr/local/lib/ruby
      if: matrix.os == 'macOS-latest'

    - name: Build Docker image
      run: docker-compose -f Dockerfile.yml build sut
      if: matrix.os == 'ubuntu-latest'

    - name: Run brew test-bot
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          docker-compose -f Dockerfile.yml run --rm -v $GITHUB_WORKSPACE:/tmp/test-bot sut
        else
          brew test-bot
        fi
      env:
        HOMEBREW_COVERALLS_REPO_TOKEN: 4MH7hVLVNactKNsGpg7bYyTUHdnGKRP5n
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run brew test-bot --dry-run tests
      run: |
        brew test-bot --ci-upload --dry-run
        brew test-bot --ci-pr https://github.com/Homebrew/brew/pull/4170 --dry-run
        brew test-bot --ci-pr https://github.com/Homebrew/brew/commit/dc96e6f73551fbadd0c2169c3a79c47a936f71ae --dry-run
      if: matrix.os == 'macOS-latest'
